name: drupal
namespace: default
imageName: drupal:8.6

initContainers:
  - name: init-sites-volume
    image: drupal:8.6
    command: ['/bin/bash', '-c']
    args: ['cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R']

serviceType: NodePort
serviceProtocol: TCP
serviceTargetPort: 80

configmap:
  enabled: true
  configmapName: drupal
  database_url: mysql-service

replicas: 1  
volumes:       
  - mountPath: /var/www/html/modules
    name: vol-drupal
    subPath: modules
    volume:
      name: vol-drupal
      persistentVolumeClaim: 
        claimName: task-pv-claim 
  - mountPath: /var/www/html/profiles
    name: vol-drupal
    subPath: profiles
    volume:
      name: vol-drupal
      persistentVolumeClaim: 
        claimName: task-pv-claim 
  - mountPath: /var/www/html/sites
    name: vol-drupal
    subPath: sites
    volume:
      name: vol-drupal
      persistentVolumeClaim: 
        claimName: task-pv-claim 
  - mountPath: /var/www/html/themes
    name: vol-drupal
    subPath: themes
    volume:
      name: vol-drupal
      persistentVolumeClaim: 
        claimName: task-pv-claim 

