name: mysql
namespace: default
imageName: mysql:5.7
env:
  - name: MYSQL_ROOT_PASSWORD
    value: root_password
  - name: MYSQL_DATABASE
    value: drupal-database

serviceType: NodePort
serviceProtocol: TCP
serviceTargetPort: 3306
volumes:
  - mountPath: /var/lib/mysql
    name: vol-drupal
    subPath: dbdata
    volume:
      name: vol-drupal
      persistentVolumeClaim: 
        claimName: mysql-pv-claim




